version: "3"

services:
    ubulatest:
        build: ./ubuntulatest
        command: "python manage.py runserver 0.0.0.0:8000"
        ports:
            - "5000:8000"

    ubuquatt:
        build: ./ubuntu14
        command: "python manage.py runserver 0.0.0.0:8000"
        ports:
            - "5014:8000"

    ubusedici:
        build: ./ubuntu16
        command: "python manage.py runserver 0.0.0.0:8000"
        ports:
            - "5016:8000"

